- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

- name: Verify docker-compose installation
  command: docker-compose --version
  register: result
  failed_when: "'Docker Compose' not in result.stdout"
  changed_when: false

